import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Patients API — Katixo Hospital OS",
  description: "Register, search, update, and retrieve patient records via the Katixo Hospital OS Patient Management API.",
};

function Endpoint({ method, path }: { method: string; path: string }) {
  const colors: Record<string, string> = {
    GET: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400",
    POST: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
    PUT: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400",
    DELETE: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400",
  };
  return (
    <div className="flex items-center gap-3 rounded-lg border border-slate-200 px-4 py-3 dark:border-white/10">
      <span className={`rounded px-2 py-0.5 text-xs font-bold ${colors[method] || ""}`}>{method}</span>
      <code className="text-sm text-slate-700 dark:text-slate-300">{path}</code>
    </div>
  );
}

export default function PatientsPage() {
  return (
    <>
      <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Patients</h1>
      <p className="mt-3 text-slate-600 dark:text-slate-400">
        Patients are the core entity in Hospital OS. Every clinical workflow — OPD consultations,
        IPD admissions, lab orders, surgeries, and billing — is linked to a patient record. On
        registration, each patient is assigned a unique{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">UHID</code>{" "}
        (Unique Hospital ID) scoped to the branch, following the format{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">KH-YYYY-NNNNN</code>.
        The UHID is auto-generated by the system and cannot be manually set. The API uses JWT
        Bearer token authentication and returns all responses in the standard{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">ApiResponse&lt;T&gt;</code>{" "}
        envelope.
      </p>

      {/* ── Authentication ── */}
      <h2 className="mt-8 text-xl font-bold text-slate-900 dark:text-white">Authentication</h2>
      <p className="mt-3 text-sm text-slate-600 dark:text-slate-400">
        All endpoints require a valid JWT Bearer token in the{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">Authorization</code> header.
      </p>
      <pre className="mt-3 overflow-x-auto rounded-lg bg-slate-900 px-5 py-4 text-sm text-slate-200">
        <code>{`Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...`}</code>
      </pre>

      {/* ── Response envelope ── */}
      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">Response envelope</h2>
      <p className="mt-3 text-sm text-slate-600 dark:text-slate-400">
        Every response is wrapped in{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">ApiResponse&lt;T&gt;</code>.
      </p>
      <pre className="mt-3 overflow-x-auto rounded-lg bg-slate-900 px-5 py-4 text-sm text-slate-200">
        <code>{`{
  "success": true,
  "message": "Patient registered successfully",
  "data": { ... },
  "errors": null
}`}</code>
      </pre>

      {/* ── Endpoints ── */}
      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">Endpoints</h2>
      <div className="mt-4 space-y-2">
        <Endpoint method="GET" path="/api/v1/patients" />
        <Endpoint method="GET" path="/api/v1/patients/{patientId}" />
        <Endpoint method="POST" path="/api/v1/patients" />
        <Endpoint method="PUT" path="/api/v1/patients/{patientId}" />
        <Endpoint method="GET" path="/api/v1/patients/{patientId}/visits" />
      </div>

      {/* ── Enums ── */}
      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">Enums</h2>

      <h3 className="mt-6 text-lg font-bold text-slate-900 dark:text-white">Gender</h3>
      <div className="mt-3 overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-slate-200 text-left dark:border-white/10">
              <th className="pb-3 pr-4 font-semibold text-slate-900 dark:text-white">Value</th>
              <th className="pb-3 font-semibold text-slate-900 dark:text-white">Description</th>
            </tr>
          </thead>
          <tbody className="text-slate-600 dark:text-slate-400">
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">MALE</code></td>
              <td className="py-2.5">Male patient.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">FEMALE</code></td>
              <td className="py-2.5">Female patient.</td>
            </tr>
            <tr>
              <td className="py-2.5 pr-4"><code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">OTHER</code></td>
              <td className="py-2.5">Other / non-binary.</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h3 className="mt-6 text-lg font-bold text-slate-900 dark:text-white">BloodGroup</h3>
      <div className="mt-3 overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-slate-200 text-left dark:border-white/10">
              <th className="pb-3 pr-4 font-semibold text-slate-900 dark:text-white">Value</th>
              <th className="pb-3 font-semibold text-slate-900 dark:text-white">Description</th>
            </tr>
          </thead>
          <tbody className="text-slate-600 dark:text-slate-400">
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">A+</code></td>
              <td className="py-2.5">A positive.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">A-</code></td>
              <td className="py-2.5">A negative.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">B+</code></td>
              <td className="py-2.5">B positive.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">B-</code></td>
              <td className="py-2.5">B negative.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">AB+</code></td>
              <td className="py-2.5">AB positive.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">AB-</code></td>
              <td className="py-2.5">AB negative.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">O+</code></td>
              <td className="py-2.5">O positive.</td>
            </tr>
            <tr>
              <td className="py-2.5 pr-4"><code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">O-</code></td>
              <td className="py-2.5">O negative.</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* ── The PatientResponse object ── */}
      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">The PatientResponse object</h2>
      <pre className="mt-3 overflow-x-auto rounded-lg bg-slate-900 px-5 py-4 text-sm text-slate-200">
        <code>{`{
  "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
  "uhid": "KH-2026-00001",
  "firstName": "Rajesh",
  "lastName": "Kumar",
  "dateOfBirth": "1985-03-15",
  "gender": "MALE",
  "phone": "+919876543210",
  "email": "rajesh.kumar@email.com",
  "address": "45 MG Road",
  "city": "Lucknow",
  "state": "Uttar Pradesh",
  "pincode": "226001",
  "bloodGroup": "B+",
  "emergencyContact": {
    "name": "Sunita Kumar",
    "phone": "+919876543211"
  },
  "aadharNumber": null,
  "abhaId": null,
  "registrationDate": "2026-06-10",
  "branchId": "a1b2c3d4-5678-9abc-def0-1234567890ab",
  "branchName": "City Hospital - Main"
}`}</code>
      </pre>

      {/* ── List / search patients ── */}
      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">List / search patients</h2>
      <div className="mt-3">
        <Endpoint method="GET" path="/api/v1/patients" />
      </div>
      <p className="mt-3 text-sm text-slate-600 dark:text-slate-400">
        Returns a paginated list of patients. Supports searching by name, phone number, or UHID.
        The response is wrapped in{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">ApiResponse&lt;Page&lt;PatientResponse&gt;&gt;</code>.
      </p>
      <h3 className="mt-4 text-base font-bold text-slate-900 dark:text-white">Query parameters</h3>
      <div className="mt-3 overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-slate-200 text-left dark:border-white/10">
              <th className="pb-3 pr-4 font-semibold text-slate-900 dark:text-white">Parameter</th>
              <th className="pb-3 pr-4 font-semibold text-slate-900 dark:text-white">Type</th>
              <th className="pb-3 pr-4 font-semibold text-slate-900 dark:text-white">Default</th>
              <th className="pb-3 font-semibold text-slate-900 dark:text-white">Description</th>
            </tr>
          </thead>
          <tbody className="text-slate-600 dark:text-slate-400">
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">search</code></td>
              <td className="py-2.5 pr-4">string</td>
              <td className="py-2.5 pr-4">--</td>
              <td className="py-2.5">Search by patient name, phone number, or UHID.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">page</code></td>
              <td className="py-2.5 pr-4">integer</td>
              <td className="py-2.5 pr-4">0</td>
              <td className="py-2.5">Zero-based page number.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">size</code></td>
              <td className="py-2.5 pr-4">integer</td>
              <td className="py-2.5 pr-4">20</td>
              <td className="py-2.5">Number of results per page.</td>
            </tr>
            <tr>
              <td className="py-2.5 pr-4"><code className="text-xs">sort</code></td>
              <td className="py-2.5 pr-4">string</td>
              <td className="py-2.5 pr-4">--</td>
              <td className="py-2.5">Sort field and direction, e.g. <code className="text-xs">registrationDate,desc</code>.</td>
            </tr>
          </tbody>
        </table>
      </div>
      <pre className="mt-4 overflow-x-auto rounded-lg bg-slate-900 px-5 py-4 text-sm text-slate-200">
        <code>{`curl -X GET "https://hospital.katixo.com/api/v1/patients?search=Rajesh&size=10&page=0" \\
  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIs..."`}</code>
      </pre>

      {/* ── Get patient ── */}
      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">Get a patient</h2>
      <div className="mt-3">
        <Endpoint method="GET" path="/api/v1/patients/{patientId}" />
      </div>
      <p className="mt-3 text-sm text-slate-600 dark:text-slate-400">
        Retrieves a single patient by UUID. Returns the full patient record wrapped in{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">ApiResponse&lt;PatientResponse&gt;</code>.
      </p>
      <pre className="mt-3 overflow-x-auto rounded-lg bg-slate-900 px-5 py-4 text-sm text-slate-200">
        <code>{`curl -X GET "https://hospital.katixo.com/api/v1/patients/f47ac10b-58cc-4372-a567-0e02b2c3d479" \\
  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIs..."`}</code>
      </pre>

      {/* ── Register patient ── */}
      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">Register a patient</h2>
      <div className="mt-3">
        <Endpoint method="POST" path="/api/v1/patients" />
      </div>
      <p className="mt-3 text-sm text-slate-600 dark:text-slate-400">
        Registers a new patient and auto-generates a UHID. Returns{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">201 Created</code> with{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">ApiResponse&lt;PatientResponse&gt;</code>.
      </p>
      <pre className="mt-4 overflow-x-auto rounded-lg bg-slate-900 px-5 py-4 text-sm text-slate-200">
        <code>{`curl -X POST "https://hospital.katixo.com/api/v1/patients" \\
  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIs..." \\
  -H "Content-Type: application/json" \\
  -d '{
    "firstName": "Priya",
    "lastName": "Sharma",
    "dateOfBirth": "1992-07-22",
    "gender": "FEMALE",
    "phone": "+919123456789",
    "email": "priya.sharma@email.com",
    "address": "12 Civil Lines",
    "city": "Jaipur",
    "state": "Rajasthan",
    "pincode": "302001",
    "bloodGroup": "O+",
    "emergencyContact": {
      "name": "Vikram Sharma",
      "phone": "+919123456780"
    },
    "aadharNumber": "9876-5432-1098",
    "abhaId": null
  }'`}</code>
      </pre>

      <h3 className="mt-8 text-lg font-bold text-slate-900 dark:text-white">CreatePatientRequest fields</h3>
      <div className="mt-4 overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-slate-200 text-left dark:border-white/10">
              <th className="pb-3 pr-4 font-semibold text-slate-900 dark:text-white">Field</th>
              <th className="pb-3 pr-4 font-semibold text-slate-900 dark:text-white">Type</th>
              <th className="pb-3 pr-4 font-semibold text-slate-900 dark:text-white">Required</th>
              <th className="pb-3 font-semibold text-slate-900 dark:text-white">Description</th>
            </tr>
          </thead>
          <tbody className="text-slate-600 dark:text-slate-400">
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">firstName</code></td>
              <td className="py-2.5 pr-4">String</td>
              <td className="py-2.5 pr-4">Yes</td>
              <td className="py-2.5">Patient&apos;s first name.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">lastName</code></td>
              <td className="py-2.5 pr-4">String</td>
              <td className="py-2.5 pr-4">Yes</td>
              <td className="py-2.5">Patient&apos;s last name.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">dateOfBirth</code></td>
              <td className="py-2.5 pr-4">LocalDate</td>
              <td className="py-2.5 pr-4">Yes</td>
              <td className="py-2.5">Date of birth in <code className="text-xs">YYYY-MM-DD</code> format.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">gender</code></td>
              <td className="py-2.5 pr-4">Gender</td>
              <td className="py-2.5 pr-4">Yes</td>
              <td className="py-2.5"><code className="text-xs">MALE</code>, <code className="text-xs">FEMALE</code>, or <code className="text-xs">OTHER</code>.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">phone</code></td>
              <td className="py-2.5 pr-4">String</td>
              <td className="py-2.5 pr-4">Yes</td>
              <td className="py-2.5">Mobile phone number with country code (e.g., <code className="text-xs">+919876543210</code>).</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">email</code></td>
              <td className="py-2.5 pr-4">String</td>
              <td className="py-2.5 pr-4">No</td>
              <td className="py-2.5">Email address.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">address</code></td>
              <td className="py-2.5 pr-4">String</td>
              <td className="py-2.5 pr-4">No</td>
              <td className="py-2.5">Street address.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">city</code></td>
              <td className="py-2.5 pr-4">String</td>
              <td className="py-2.5 pr-4">No</td>
              <td className="py-2.5">City name.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">state</code></td>
              <td className="py-2.5 pr-4">String</td>
              <td className="py-2.5 pr-4">No</td>
              <td className="py-2.5">State name (e.g., &quot;Uttar Pradesh&quot;).</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">pincode</code></td>
              <td className="py-2.5 pr-4">String</td>
              <td className="py-2.5 pr-4">No</td>
              <td className="py-2.5">6-digit PIN code.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">bloodGroup</code></td>
              <td className="py-2.5 pr-4">BloodGroup</td>
              <td className="py-2.5 pr-4">No</td>
              <td className="py-2.5">Blood group. See enum above.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">emergencyContact</code></td>
              <td className="py-2.5 pr-4">Object</td>
              <td className="py-2.5 pr-4">No</td>
              <td className="py-2.5">Emergency contact with <code className="text-xs">name</code> (String) and <code className="text-xs">phone</code> (String) fields.</td>
            </tr>
            <tr className="border-b border-slate-100 dark:border-white/5">
              <td className="py-2.5 pr-4"><code className="text-xs">aadharNumber</code></td>
              <td className="py-2.5 pr-4">String</td>
              <td className="py-2.5 pr-4">No</td>
              <td className="py-2.5">12-digit Aadhaar number (formatted as <code className="text-xs">XXXX-XXXX-XXXX</code>).</td>
            </tr>
            <tr>
              <td className="py-2.5 pr-4"><code className="text-xs">abhaId</code></td>
              <td className="py-2.5 pr-4">String</td>
              <td className="py-2.5 pr-4">No</td>
              <td className="py-2.5">ABDM (Ayushman Bharat Digital Mission) health ID for digital health record linking.</td>
            </tr>
          </tbody>
        </table>
      </div>

      {/* ── Update patient ── */}
      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">Update a patient</h2>
      <div className="mt-3">
        <Endpoint method="PUT" path="/api/v1/patients/{patientId}" />
      </div>
      <p className="mt-3 text-sm text-slate-600 dark:text-slate-400">
        Updates an existing patient&apos;s details. The request body uses the same{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">CreatePatientRequest</code>{" "}
        schema. The <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">uhid</code> and{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">registrationDate</code> cannot
        be modified. Returns{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">ApiResponse&lt;PatientResponse&gt;</code>.
      </p>
      <pre className="mt-4 overflow-x-auto rounded-lg bg-slate-900 px-5 py-4 text-sm text-slate-200">
        <code>{`curl -X PUT "https://hospital.katixo.com/api/v1/patients/f47ac10b-58cc-4372-a567-0e02b2c3d479" \\
  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIs..." \\
  -H "Content-Type: application/json" \\
  -d '{
    "firstName": "Rajesh",
    "lastName": "Kumar",
    "dateOfBirth": "1985-03-15",
    "gender": "MALE",
    "phone": "+919876543210",
    "email": "rajesh.kumar@newmail.com",
    "address": "72 Hazratganj",
    "city": "Lucknow",
    "state": "Uttar Pradesh",
    "pincode": "226001",
    "bloodGroup": "B+",
    "emergencyContact": {
      "name": "Sunita Kumar",
      "phone": "+919876543211"
    },
    "aadharNumber": "1234-5678-9012",
    "abhaId": "rajesh.kumar@abdm"
  }'`}</code>
      </pre>

      {/* ── Visit history ── */}
      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">Get visit history</h2>
      <div className="mt-3">
        <Endpoint method="GET" path="/api/v1/patients/{patientId}/visits" />
      </div>
      <p className="mt-3 text-sm text-slate-600 dark:text-slate-400">
        Retrieves the complete visit history for a patient, including both OPD (outpatient) and IPD
        (inpatient) records. Returns{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">ApiResponse&lt;List&lt;VisitResponse&gt;&gt;</code>.
      </p>
      <pre className="mt-3 overflow-x-auto rounded-lg bg-slate-900 px-5 py-4 text-sm text-slate-200">
        <code>{`curl -X GET "https://hospital.katixo.com/api/v1/patients/f47ac10b-58cc-4372-a567-0e02b2c3d479/visits" \\
  -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIs..."`}</code>
      </pre>
      <h3 className="mt-6 text-lg font-bold text-slate-900 dark:text-white">Example response</h3>
      <pre className="mt-3 overflow-x-auto rounded-lg bg-slate-900 px-5 py-4 text-sm text-slate-200">
        <code>{`{
  "success": true,
  "message": "Visit history retrieved",
  "data": [
    {
      "visitId": "b2c3d4e5-6789-abcd-ef01-234567890abc",
      "type": "OPD",
      "visitDate": "2026-06-10",
      "department": "General Medicine",
      "doctorName": "Dr. Anita Verma",
      "diagnosis": "Acute viral fever",
      "status": "COMPLETED"
    },
    {
      "visitId": "c3d4e5f6-789a-bcde-f012-34567890abcd",
      "type": "IPD",
      "admissionDate": "2026-05-01",
      "dischargeDate": "2026-05-05",
      "department": "Orthopaedics",
      "doctorName": "Dr. Manoj Tiwari",
      "diagnosis": "Fracture - left tibia",
      "ward": "General Ward - A",
      "bedNumber": "GW-A-14",
      "status": "DISCHARGED"
    }
  ],
  "errors": null
}`}</code>
      </pre>

      {/* ── Error responses ── */}
      <h2 className="mt-10 text-xl font-bold text-slate-900 dark:text-white">Error responses</h2>
      <p className="mt-3 text-sm text-slate-600 dark:text-slate-400">
        When validation fails or a resource is not found, the API returns an{" "}
        <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">ApiResponse</code>{" "}
        with <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">success: false</code>{" "}
        and the <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs dark:bg-white/10">errors</code> array
        populated.
      </p>
      <pre className="mt-3 overflow-x-auto rounded-lg bg-slate-900 px-5 py-4 text-sm text-slate-200">
        <code>{`{
  "success": false,
  "message": "Validation failed",
  "data": null,
  "errors": [
    "firstName: must not be blank",
    "phone: must not be blank",
    "gender: must not be null"
  ]
}`}</code>
      </pre>
    </>
  );
}
